### ISSUE TITLE
Using VSIX to distribute a solution template with discovery via the "Create a new project" interface

### ISSUE THREAD

**Issue by archubbuck** [sayedihashimi/template-sample#19]
It is our goal to be able to create a solution template that contains multiple projects, install that template using VSIX, and then access the solution template via the "Create a new project" interface. 

Do you know when Microsoft will introduce support for accessing solution templates via the "Create a new project" window? 

I used your example in this repository to create a solution template that's accessible via the dotnet CLI, but the dotnet CLI alone doesn't offer a way in which we can easily distribute templates across the organization.

Thank you in advance for any insight you can provide, @sayedihashimi.

**Comment by sayedihashimi** [comment]
@archubbuck solution support is in the latest previews of VS2019 v16.10.

In the readme of this repo this section should be helpful for your scenario https://github.com/sayedihashimi/template-sample#how-to-ship-a-template-inside-of-a-visual-studio-extension-vsix, and there is a sample at https://github.com/sayedihashimi/template-sample/tree/main/src/Content/SolutionTemplate

Please try it with the latest preview of Visual Studio, and if you're not able to get it to work, reply here.

I'm going to close this issue, because I believe that I've answered your question, and the support is there. If I've misunderstood, please reopen with some additional info.

**Comment by archubbuck** [comment]
Thanks @sayedihashimi. I've been able to get this working in Visual Studio Preview. 

Do you know when VS2019 v16.10 will be GA?

**Comment by sayedihashimi** [comment]
I am not at liberty to say specifically when it will be released, but it's not too far from now. Can we close this issue, or is there more that needs to be addressed?

**Comment by archubbuck** [comment]
> I am not at liberty to say specifically when it will be released, but it's not too far from now.

Thanks @sayedihashimi and I understand the caution. My team will be glad to hear this is a feature that will be available very soon.

**Comment by vondwater** [comment]
Hi @sayedihashimi,

Sorry for responding on this closed issue but I'm experiencing some troubles with creating a vsix.

I'm trying to create a vsix project to install the templates but the templates are not shown after installation when I try to create a new project from it. I already tried with the vsix sample project in the repository but I have no luck with that either.

Am I doing something wrong?

The extensions are shown in the extensions manager, so that part works.

![image](https://user-images.githubusercontent.com/841864/125085907-61e03a80-e0cb-11eb-900d-052921a13360.png)
The blue circled one is mine.

When I install the template with dotnet new the template does show up in the "create new project" wizard.

**Comment by sayedihashimi** [comment]
@vondwater can you share the vsix? I will try it out.

**Comment by vondwater** [comment]
Hi @sayedihashimi, I'm sorry for the late response.
You can find the vsix and .nupkg here:
shorturl.at/rGL46

**Comment by sayedihashimi** [comment]
@vondwater I'm not seeing any content at that URL, can you check it?

**Comment by vondwater** [comment]
I'm sorry, maybe this link then:
https://abiware-my.sharepoint.com/:f:/g/personal/jvdw_abiware_be/EsoCdz8qb4pDucSYxYmN2b0BIHgKF_kOUJNZAsNnBVbx4A?e=flRwa7

**Comment by sayedihashimi** [comment]
@vondwater did you follow all the steps listed at https://github.com/sayedihashimi/template-sample#adding-a-pkgdef-file? I'm not seeing the `Templates.pkgdef` file. If you added this file to your project, but it's not included in the generated vsix make sure that the `Build Action` is set to `Content` for the pkgdef file. See the image below.

![image](https://user-images.githubusercontent.com/1283154/125325643-2afa6680-e30f-11eb-9233-daadb9bc50ae.png)

**Comment by vondwater** [comment]
@sayedihashimi I have provided the solution in that shared folder on onedrive. I've put that .pkgdef file in my solution and also changed the build action to 'Content'. 
But after installing the vsix I still don't see the project template.

**Comment by sayedihashimi** [comment]
@vondwater let's move the discussion to a new issue that I just created https://github.com/sayedihashimi/template-sample/issues/37.
