### ISSUE TITLE
dotnetnew.azurewebsites.net update schedule

### ISSUE THREAD

**Issue by bboy77** [sayedihashimi/template-sample#63]
HI,

How often does dotnetnew.azurewebsites.net update current template packages?

 I currently have old versions on the site and would like to have the following package uploaded if possible.

https://www.nuget.org/packages/AebSolutions.CodeConvention.SolutionTemplates version 6.6.0

**Comment by sayedihashimi** [comment]
It should update every night, but I’ve noticed that in some cases I have to special case packages to get picked up. I made a change https://github.com/sayedihashimi/dotnet-new-web/commit/a470a33e8ca503c3c0a80d996c44807148eb82fd that should hopefully pick it up. I’m on vacation so don’t have access to a PC to manually kick it off. It it’s not updated tomorrow this time, please comment here and I will take a look when I’m back home.

**Comment by sayedihashimi** [comment]
It looks like it’s there https://dotnetnew.azurewebsites.net/pack/AebSolutions.CodeConvention.SolutionTemplates are you saying that the info displayed isn’t updated?

**Comment by bboy77** [comment]
It shows 6 templates with outdated descriptions currently. I have 7 templates with the most important one being
https://github.com/bboy77/Templates/tree/main/SolutionTemplates/Content/Multi-ProjectEx/. 

I believe the template links are from last fall.

**Comment by sayedihashimi** [comment]
I will have to take a look when I get back. Sorry this is happening.

**Comment by bboy77** [comment]
Thanks for the response, I appreciate it.

**Comment by sayedihashimi** [comment]
Hi @bboy77, I figured out what the problem was. My CI build was broken for the past 20 days, so the website wasn't getting updated 🤣🤣🤣🤣. It broke right before I went on vacation.

Sorry about that. After fixing the build, I verified that your latest package was appearing in the download log and that there are 7 templates appearing on the website https://dotnetnew.azurewebsites.net/pack/AebSolutions.CodeConvention.SolutionTemplates.

Typically, the website gets updated every night from my CI build. I didn't notice it was broken somehow. My apologies for that.

I'll close this issue, but if it's still not correct please let me know.

**Comment by bboy77** [comment]
Everything looks great, thanks again!

I have enjoyed creating templates for the last few years and your content and tutorials online got me started.

**Comment by sayedihashimi** [comment]
Thanks @bboy77, that is really great to hear. Please let me know if you have any questions in the future.
