### ISSUE TITLE
Item Template replace Namespace with that from the Project and folder it is added

### ISSUE THREAD

**Issue by james1301** [sayedihashimi/template-sample#70]
Hi, I understand it is pretty straightforward for a Project Template to use the name entered for the project to replace the namespace. But for an Item Template, how would you do this as it needs to come from the project and folder it is added into?

**Comment by sayedihashimi** [comment]
@phenning what's the syntax for getting the namespace in an item template?

**Comment by phenning** [comment]
The Maui item templates are a good example of this:
https://github.com/dotnet/maui/tree/main/src/Templates/src/templates/maui-contentpage-csharp

In .cs file:
`namespace AppName.Namespace;`

in template.json:
```
    "symbols": {
      "namespace": {
        "description": "Namespace for the generated code.",
        "replaces": "AppName.Namespace",
        "type": "parameter"
      }
    }
```
    
Visual Studio will recognize this symbol and automatically generate a safe namespace which includes the folder into which thetemplate is being generated.

There is another syntax which is supported by the dotnet new as of NET 7 as well. Visual Studio also supports this, but it uses the  msbuild RootNamespace property only instead of using the folder name in the namespace. This is documented here:

https://github.com/dotnet/templating/wiki/Binding-and-project-context-evaluation#binding-to-msbuild-properties

**Comment by james1301** [comment]
Cool thanks, @sayedihashimi and @phenning.
