### ISSUE TITLE
Item Template Open File in Editor on Create

### ISSUE THREAD

**Issue by james1301** [sayedihashimi/template-sample#71]
Hi, last thing I think 🙂. I saw there was code for opening an item template in the editor here: [Post-Action-Registry](https://github.com/dotnet/templating/wiki/Post-Action-Registry), but I can't seem to get it to work.

Basically wanting it to open up the single c# class created. I have added this element but it doesn't seem to do anything when I create the item through the Visual Studio Add Item screen.

`"postActions": [
  {
    "condition": "(HostIdentifier != \"dotnetcli\")",
    "description": "Opens Class1.cs in the editor",
    "manualInstructions": [ ],
    "actionId": "84C0DA21-51C8-4541-9940-6CA19AF04EE6",
    "args": {
      "files": "1"
    },
    "continueOnError": true
  }
]`

**Comment by sayedihashimi** [comment]
@james1301 when you create files from the VS Add New Item Dialog, that file(s) should open in the editor without customizations. What behavior are you seeing? Please be specific.

**Comment by james1301** [comment]
Right-click on my C# project, go to Add New Item, navigate to my item template and click Add. The new class gets added to my project but does not open up. If I do the standard class template it opens up as expected.

**Comment by james1301** [comment]
Using latest non-preview Visual Studio 17.4.3.

**Comment by james1301** [comment]
That link I sent, suggests that is how to do it for non-command line cases.

![image](https://user-images.githubusercontent.com/17780517/208622650-aca10139-1df4-4043-a8f0-d77549078d2d.png)

**Comment by sayedihashimi** [comment]
@james1301 what version of Visual Studio are you using? FYI the whole team (me included) is on vacation so responses may be delayed.

**Comment by phenning** [comment]
Actually, we do require the open post action to be present in the template. 

@james1301 do you have the file generated by the template listed as a primary output?

 If it is the only one, “files” in the post action should be set to 0 since it is a zero based index. 

As an aside, it would be interesting to have item templates which generate a single file to not require a post action to open the file in Visual Studio. I think we’d need to have a way to have authors opt out, and they would need to have it anyway for older versions of VS and VSMac, or if there were multiple files you may not want to have them all opened.

**Comment by james1301** [comment]
Thanks @phenning and @sayedihashimi I have got this working with adding the Primary output section, Maybe should have noticed that bit 🙂. Yeah would be more simple for item templates to not need this.

Thanks again for all of your help, I think my templates are all how I want them for the moment 🙂. Replaced our old template process which was terrible to update anything and unclear from source control point of view.
